valory-xyz/autonolas-contribution-service-frontend

- common-util/meta.jsx
> fix: twitter title meta 

- components/Layout/Footer.jsx
- components/Layout/styles.jsx
- package.json
- yarn.lock
> feat: update widget component

- package.json
- yarn.lock
* "Get help building" to point to autonolas website's ecosystem builder
https://github.com/valory-xyz/autonolas-contribution-service-frontend/assets/22061815/bf514c15-a299-418f-8dc0-b6330aa73cf5
> feat: update package for service info status

- common-util/Contracts/index.jsx
- common-util/Login/LoginV2.jsx
- common-util/Login/config.jsx
https://github.com/valory-xyz/autonolas-contribution-service-frontend/assets/22061815/700298e0-9ac9-4642-b24c-dee8f9c14c1b
> feat: update wallet connect

- components/Chatbot/ChatbotCard.jsx
- components/CoOrdinate/Centaur/hooks.jsx
- components/Dashboard/index.jsx
- components/Leaderboard/LeaderboardCard.jsx
- components/Leaderboard/index.jsx
- components/Members/MembersCard.jsx
- components/Profile/ProfileCard.jsx
- components/Tweet/TweetCard.jsx
> adds all cards

- common-util/Contracts/index.jsx
- common-util/Education/data.json
- common-util/functions/index.jsx
- common-util/prop-types.js
- components/CoOrdinate/Centaur/hooks.jsx
- components/GroupChat/index.jsx
- components/GroupChat/styles.jsx
- components/Proposals/Proposal.jsx
- components/Tweet/TweetCard.jsx
- components/Tweet/index.jsx
- util/constants.jsx
TODO: need to test once the backend is compatible with voters
example:
* total veOlas still remaining
* total veOlass max
> feat: update approval functionality 

- components/Documentation/content/Proposals.jsx
> feat: "Proposal" doc text update

- common-util/Login/LoginV2.jsx
- components/Dashboard/index.jsx
- components/GlobalStyles/index.jsx
- components/Layout/Footer.jsx
- components/Layout/index.jsx
- components/Layout/styles.jsx
- components/Leaderboard/Actions/index.jsx
- components/Leaderboard/LeaderboardTable/index.jsx
- components/Leaderboard/MintNft/styles.jsx
- components/Leaderboard/index.jsx
- components/Members/index.jsx
- components/Roadmap/index.jsx
- components/Tweet/index.jsx
- next.config.js
- pages/roadmap.jsx
This PR aims to add a Roadmap page to Contribute to allow people to see what's on the horizon for Olas.
There are two main parts:
- [add the page itself](https://github.com/valory-xyz/autonolas-contribution-service-frontend/commit/fff54bbbaf39a7397d0ca69309dfa7026532d855)
- [refactor the menu to support another item, and fix downstream UX issues](https://github.com/valory-xyz/autonolas-contribution-service-frontend/commit/fff54bbbaf39a7397d0ca69309dfa7026532d855)
> Add Roadmap page

- common-util/Education/data.json
- components/Calendar/EventPage.jsx
- components/Documentation/content/Predict.jsx
- components/Documentation/helpers.jsx
- components/Documentation/index.jsx
- components/Predict/PredictionForm.jsx
- components/Predict/PredictionRequestsTable.jsx
- components/Roadmap/index.jsx
> adds documentation for Contribute Predict

- components/Calendar/events.json
- components/Calendar/index.jsx
> Add new events to Calendar

- common-util/functions/index.jsx
- common-util/hooks/useOrbis.jsx
- common-util/prop-types.js
- components/Chat/index.jsx
- components/GroupChat/EmptyStateMessage.jsx
- components/GroupChat/MessageGroupContainer.jsx
- components/GroupChat/MessageGroups.jsx
- components/GroupChat/MessageInput.jsx
- components/GroupChat/VeolasModal.jsx
- components/GroupChat/index.jsx
- components/Layout/index.jsx
- components/Layout/styles.jsx
- components/MembersList/requests.jsx
- components/Predict/PredictionRequestsTable.jsx
- components/Tweet/Proposals/ExecuteStep.jsx
- components/Tweet/Proposals/index.jsx
- components/Tweet/index.jsx
Please check the commit messages – they're descriptive of the changes.
Note: the fix was to fix an issue where messages were being incorrectly grouped. I refactored in order to reason properly about it.
> Chore chat followup

- components/Calendar/events.json
- components/Calendar/index.jsx
on behalf of [adrianoVal](https://github.com/adrianoVal)
> Update calendar dates and add link to WiO

- components/VotingPower/hooks.js
> Fix delegated to you not visible

- components/Tweet/Proposals/Proposal.jsx
The problem was in that we used `set` for mutating object but i's been frozen so the changes didn't apply
> Fix tweet execution

- components/Leaderboard/Actions/data.json
> Add #StakeWithPearl to the actions description

- common-util/functions/time.js
Possibly fixing this error for one of the users from discord
> fix: date format fix

- components/Profile/HowTweetsAreScoredModal.jsx
- components/Profile/Staking.jsx
- package.json
- yarn.lock
Adds how your tweets are scored modal to staking section
| Link      | Modal |
| ----------- | ----------- |
| <img width="770" alt="Screenshot 2024-12-09 at 14 42 30" src="https://github.com/user-attachments/assets/7698044e-fabd-4bf7-908d-ca6c1e49185e">      | <img width="1038" alt="Screenshot 2024-12-09 at 14 46 13" src="https://github.com/user-attachments/assets/0f8c0aef-ea95-4edd-ab47-d1e532a4d3c5">       |
| Link      | Modal |
| ----------- | ----------- |
| <img width="428" alt="Screenshot 2024-12-09 at 14 46 55" src="https://github.com/user-attachments/assets/9028d1be-8154-4f91-8164-2c41bb70279a">      | <img width="414" alt="Screenshot 2024-12-09 at 14 47 04" src="https://github.com/user-attachments/assets/0ff4b9c8-c6f3-4284-9de4-1813ecc5a945">       |
> feat: add how your tweets are scored modal

- components/Profile/HowTweetsAreScoredModal.jsx
> chore: update modal text

- components/Leaderboard/Campaigns/index.jsx
Added description dropdowns for each hashtag in the campaigns table.
> style: added dropdowns for campaigns table

- components/Layout/index.jsx
- components/Staking/index.jsx
- util/staking.js
there's an issue in the current staking contracts preventing users from complete unstaking. temporarily hide the feature so that there are no new joiners. will incorporate new contracts next week
> chore: hide staking

- common-util/AbiAndAddresses/contributors.ts
- components/Profile/Staking/index.tsx
- components/Staking/StakingStepper.tsx
- components/Staking/WalletUpdateRequired.tsx
- util/constants.ts
> feat: add locked users modal

- components/GlobalStyles/index.jsx
- components/Layout/index.jsx
Added header dropdown for users to navigate between subsites better.
> feat: added header dropdown for easier navigation between sites

- next.config.js
Small SEO fix for SEMrush: added en locale.
> chore: added hreflang and lang locale
